local mod = get_mod("Peregrinaje")

mod:add_text("huntsman_pinpoint_accuracy", "Hip Fire Expert")
mod:add_text("huntsman_pinpoint_accuracy_desc", "Makes all ranged attacks pin point accurate and removes aim punch.")
mod:add_text("multishoot_description", "Your ranged attacks fire 2 additional projectiles, but your power, attack speed, and reload speed with ranged weapons is reduced by 15%.")
mod:add_text("slower_description", "Power increased by 45%. Attack and reload speed decreased by 15%.")
mod:add_text("description_attack_speed_per_coins", "Attack speed increases by 1% for every 400 coins that you have, up to 127%.")
mod:add_text("cringemod_regrowth_name", "Crit/HS Thp")
mod:add_text("cringemod_cleave_thp_name", "Multi Hit Thp")
mod:add_text("cringemod_cleave_thp_desc", "You gain 1 temp health when hitting an enemy, up to 5 enemies per attack.")
mod:add_text("rebaltourn_career_passive_name_dr_2d", "Path of Carnage")
mod:add_text("rebaltourn_career_passive_desc_dr_2d_2", "Reduces damage taken by 10% and increases attack speed by 7.5%.")
mod:add_text("engi_2_1_cdr_name", "Considerably Less Ingenious Ordnance")
mod:add_text("engi_2_1_cdr_desc", "Gain cooldown regeneration equivalent to one crank at all times.")
mod:add_text("kerillian_waywatcher_passive_restore_ammo", "Bottomless Quiver")
mod:add_text("kerillian_waywatcher_passive_restore_ammo_desc", "Amaranthe also restores 5% ammunition every tick.\n\nI'm testing how to add new talents to Peregrinaje\n~Hazard")
mod:add_text("victor_bountyhunter_activated_ability_blast_shotgun_desc", "Modifies Victor's sidearm to fire two blasts of shield-penetrating pellets in a devastating cone. Reduces cooldown of Locked and Loaded by 25%%. Gain 5%% ammo on ranged citical hit.")
mod:add_text("cringemod_kerillian_waywatcher_extra_arrow_melee_kill_desc", "After killing an enemy with a melee attack, your next ranged attack within 10 seconds fires 3 additional arrows.")
mod:add_text("cringe_career_passive_name_necro", "Divine Punishment")
mod:add_text("cringe_career_passive_desc_necro", "For betraying Myrmidia and changing school, the necrotic cold weakened Sienna's body. Power reduced by 25%. Attack speed reduced by 10%. However, she can command powerful skeletons.")
mod:echo("Added cringe to your pere")
